# Generated by Django 5.0.4 on 2024-04-12 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='otp_code',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afd15731-6094-46f7-9790-7e8f5f3a9726'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8f79ee0-9551-4569-bb83-86fe174ec413'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
