# Generated by Django 5.0.4 on 2024-04-12 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_otpverification_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='is_expired',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b9f39691-dccb-49f9-86d1-6fdbcf826536'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c9163aca-ba1a-44a3-8559-0cce2405ba20'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
