# Generated by Django 5.0.4 on 2024-04-13 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers_rename_is_staff_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e5b1099-9d6f-4d45-ad32-e52e8b3de715'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94a102b0-1a10-4add-b55b-93ff5ac1ad71'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
